In [40]:
import pandas as pd
import numpy as np

In [41]:
riders = pd.read_csv("../dataset/riders.csv")

print(riders.shape)
riders.head()

(45584, 20)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [42]:
missing = pd.DataFrame({
    "Missing": riders.isnull().sum(),
    "Percent": round(riders.isnull().mean()*100,2)
})

missing.sort_values("Percent", ascending=False)

                             Missing  Percent
Delivery_person_Ratings         1908     4.19
Delivery_person_Age             1854     4.07
Time_Orderd                     1731     3.80
City                            1200     2.63
multiple_deliveries              993     2.18
Weather_conditions               616     1.35
Road_traffic_density             601     1.32
Festival                         228     0.50
ID                                 0     0.00
Type_of_vehicle                    0     0.00
Type_of_order                      0     0.00
Vehicle_condition                  0     0.00
Time_Order_picked                  0     0.00
Delivery_person_ID                 0     0.00
Order_Date                         0     0.00
Delivery_location_longitude        0     0.00
Delivery_location_latitude         0     0.00
Restaurant_longitude               0     0.00
Restaurant_latitude                0     0.00
Time_taken (min)                   0     0.00

In [43]:
riders.replace(
    ["NaN", "nan", "NULL", "None", ""],
    np.nan,
    inplace=True
)

In [44]:
num_cols = [
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "multiple_deliveries"
]

for col in num_cols:
    riders[col] = riders[col].fillna(riders[col].median())

In [45]:
cat_cols = [
    "Weather_conditions",
    "Road_traffic_density",
    "Festival",
    "City"
]

for col in cat_cols:
    riders[col] = riders[col].fillna(riders[col].mode()[0])

In [46]:
riders["Time_Orderd"] = riders["Time_Orderd"].fillna(
    riders["Time_Order_picked"]
)

In [47]:
riders["Time_Orderd"] = riders["Time_Orderd"].astype(str).str.strip()

riders["Time_Order_picked"] = riders["Time_Order_picked"].astype(str).str.strip()

In [48]:
riders["Order_Date"] = pd.to_datetime(
    riders["Order_Date"],
    format="%d-%m-%Y"
)

In [49]:
riders = riders[
    riders["Delivery_person_Ratings"].between(1, 5)
]

In [50]:
riders = riders[
    riders["Delivery_person_Age"].between(18, 60)
]

In [51]:
print("Duplicates:", riders.duplicated().sum())

riders = riders.drop_duplicates()

Duplicates: 0

In [52]:
print(riders.shape)

print("\nMissing Values")
print(riders.isnull().sum())

print("\nData Types")
print(riders.dtypes)

print("\nSample Time Values")
print(riders[["Time_Orderd", "Time_Order_picked"]].head())

(45493, 20)

Missing Values
ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken (min)               0
dtype: int64

Data Types
ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                            object
Time_Order_picked                      object
Weather_conditions                     object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                   float64
Festival                               object
City                                   object
Time_taken (min)                        int64
dtype: object

Sample Time Values
  Time_Orderd Time_Order_picked
0       21:55             22:10
1       14:55             15:05
2       17:30             17:40
3       09:20             09:30
4       19:50             20:05

In [54]:
riders.to_csv(
    "../dataset/processed/riders_clean.csv",
    index=False
)